
import java.io.BufferedWriter;
import java.io.FileOutputStream;
import java.io.OutputStreamWriter;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author DELL 3520
 */
public class FormSV extends javax.swing.JFrame {

    ArrayList<SinhVienATTT> listAT=new ArrayList<>();
    ArrayList<SinhVienMM> listMM=new ArrayList<>();
    SinhVienATTT at=new SinhVienATTT();
    SinhVienMM mm=new SinhVienMM();
    /**
     * Creates new form FormSV
     */
    public FormSV() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jRadioButton1 = new javax.swing.JRadioButton();
        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        tluong = new javax.swing.JTextField();
        tdv = new javax.swing.JTextField();
        thp = new javax.swing.JTextField();
        tdiem = new javax.swing.JTextField();
        tns = new javax.swing.JTextField();
        tma = new javax.swing.JTextField();
        tht = new javax.swing.JTextField();
        rnam = new javax.swing.JRadioButton();
        rat = new javax.swing.JRadioButton();
        rmm = new javax.swing.JRadioButton();
        rnu = new javax.swing.JRadioButton();
        add = new javax.swing.JButton();
        save = new javax.swing.JButton();
        clear = new javax.swing.JButton();

        jRadioButton1.setText("jRadioButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Ma SV");

        jLabel2.setText("Ho ten");

        jLabel3.setText("Ngay sinh");

        jLabel4.setText("Gioi tinh");

        jLabel5.setText("Diem TB");

        jLabel6.setText("Loai SV");

        jLabel7.setText("Hoc phi");

        jLabel8.setText("Luong");

        jLabel9.setText("Don vi");

        jLabel10.setText("QLSV");

        buttonGroup1.add(rnam);
        rnam.setText("Nam");

        buttonGroup2.add(rat);
        rat.setText("SVAT");
        rat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ratActionPerformed(evt);
            }
        });

        buttonGroup2.add(rmm);
        rmm.setText("SVMM");
        rmm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rmmActionPerformed(evt);
            }
        });

        buttonGroup1.add(rnu);
        rnu.setText("Nu");

        add.setText("Them");
        add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addActionPerformed(evt);
            }
        });

        save.setText("Luu");
        save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveActionPerformed(evt);
            }
        });

        clear.setText("Xoa");
        clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(tdv, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(tluong, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(thp, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(tdiem, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(tma, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(tht, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel6)
                            .addComponent(jLabel4))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(rnam)
                                        .addGap(63, 63, 63)
                                        .addComponent(rnu))
                                    .addComponent(tns, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(39, 39, 39)
                                .addComponent(rat)
                                .addGap(53, 53, 53)
                                .addComponent(rmm)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addGap(35, 35, 35))
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(add)
                .addGap(59, 59, 59)
                .addComponent(save)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(clear)
                .addGap(59, 59, 59))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel10)
                .addGap(171, 171, 171))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabel10)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tht, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tns, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(rnam)
                    .addComponent(rnu))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(tdiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(rat)
                    .addComponent(rmm))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(thp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(tluong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(tdv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(add)
                    .addComponent(save)
                    .addComponent(clear))
                .addGap(23, 23, 23))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addActionPerformed
        // TODO add your handling code here:
        if(!rat.isSelected() && !rmm.isSelected()){
            JOptionPane.showMessageDialog(this, "Vui long chon loai SV","ERROR",JOptionPane.ERROR_MESSAGE);
        }else{
            if(rat.isSelected()){
                if(kiemtraAT()==false){
                    at.setMaSV(tma.getText());
                    at.setHoTen(tht.getText());
                    at.setNgaySinh(tns.getText());
                    at.setDiemTB(Float.parseFloat(tdiem.getText()));
                    at.setHocPhi(Float.parseFloat(thp.getText()));
                    if(rnam.isSelected()){
                        at.setGioiTinh("Nam");
                    }
                    else{
                        at.setGioiTinh("Nu");
                    }
                    listAT.add(at);
                    System.out.println(at.toString());
                    JOptionPane.showMessageDialog(this, "Them thanh cong");
                }
                else{
                    JOptionPane.showMessageDialog(this, "Vui long nhap day du thong tin","ERROR",JOptionPane.ERROR_MESSAGE);
                    }
            }
            else if(rmm.isSelected()){
                if(kiemtraMM()==false){
                    mm.setMaSV(tma.getText());
                    mm.setHoTen(tht.getText());
                    mm.setNgaySinh(tns.getText());
                    mm.setDvi(tdv.getText());
                    mm.setDiemTB(Float.parseFloat(tdiem.getText()));
                    mm.setLuong(Float.parseFloat(tluong.getText()));
                    if(rnam.isSelected()){
                        at.setGioiTinh("Nam");
                    }
                    else{
                        at.setGioiTinh("Nu");
                    }
                    listMM.add(mm);
                    System.out.println(mm.toString());
                    JOptionPane.showMessageDialog(this, "Them thanh cong");
                }
                else{
                    JOptionPane.showMessageDialog(this, "Vui long nhap day du thong tin","ERROR",JOptionPane.ERROR_MESSAGE);
                    }
            }
        }
    }//GEN-LAST:event_addActionPerformed

    private void saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveActionPerformed
        // TODO add your handling code here:
        ghiFile();
    }//GEN-LAST:event_saveActionPerformed

    private void clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearActionPerformed
        // TODO add your handling code here:
        tma.setText("");
        tht.setText("");
        tns.setText("");
        tdiem.setText("");
        thp.setText("");
        tluong.setText("");
        tdv.setText("");
        buttonGroup1.clearSelection();
        buttonGroup2.clearSelection();
    }//GEN-LAST:event_clearActionPerformed

    private void ratActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ratActionPerformed
        // TODO add your handling code here:
        thp.setEnabled(true);
        tdv.setEnabled(false);
        tluong.setEnabled(false);
        thp.setText("");
    }//GEN-LAST:event_ratActionPerformed

    private void rmmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rmmActionPerformed
        // TODO add your handling code here:
        thp.setEnabled(false);
        tdv.setEnabled(true);
        tluong.setEnabled(true);
        tdv.setText("");
        tluong.setText("");
    }//GEN-LAST:event_rmmActionPerformed

    public void ghiFile(){
        try {
            FileOutputStream fos=new FileOutputStream("sinhvienAT.txt");
            OutputStreamWriter osw=new OutputStreamWriter(fos);
            BufferedWriter bw=new BufferedWriter(osw);
            String line="";
            for(SinhVienATTT attt:listAT){
                line+=attt.getMaSV();
                line+=attt.getHoTen();
                line+=attt.getNgaySinh();
                line+=attt.getDiemTB();
                line+=attt.getHocPhi();
                if(rnam.isSelected()){
                    line+="Nam";
                }else{
                    line+="Nu";
                }
                bw.write(line);
                bw.newLine();
                
            }
            JOptionPane.showMessageDialog(this, "luu thanh cong");
            bw.close();
            osw.close();
            fos.close();
            
        } catch (Exception e) {
        }
        
        try {
            FileOutputStream fos=new FileOutputStream("sinhvienMM.txt");
            OutputStreamWriter osw=new OutputStreamWriter(fos);
            BufferedWriter bw=new BufferedWriter(osw);
            String line="";
            for(SinhVienMM svmm:listMM){
                line+=svmm.getMaSV();
                line+=svmm.getHoTen();
                line+=svmm.getNgaySinh();
                line+=svmm.getDiemTB();
                line+=svmm.getDvi();
                line+=svmm.getLuong();
                if(rnam.isSelected()){
                    line+="Nam";
                }else{
                    line+="Nu";
                }
                bw.write(line);
                bw.newLine();
            }
            JOptionPane.showMessageDialog(this, "luu thanh cong");
            bw.close();
            osw.close();
            fos.close();
        } catch (Exception e) {
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormSV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormSV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormSV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormSV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormSV().setVisible(true);
            }
        });
    }
    
    public boolean kiemtraAT(){
        if(tma.getText().equals("")||tht.getText().equals("")||tns.getText().equals("")||tdiem.getText().equals("")||thp.getText().equals("")||(!rnam.isSelected()&&!rnu.isSelected())){
            return true;
        }else
            return false;
    }
    
    public boolean kiemtraMM(){
        if(tma.getText().equals("")||tht.getText().equals("")||tns.getText().equals("")||tdiem.getText().equals("")||tdv.getText().equals("")||tluong.getText().equals("")||(!rnam.isSelected()&&!rnu.isSelected())){
            return true;
        }else
            return false;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton add;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JButton clear;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton rat;
    private javax.swing.JRadioButton rmm;
    private javax.swing.JRadioButton rnam;
    private javax.swing.JRadioButton rnu;
    private javax.swing.JButton save;
    private javax.swing.JTextField tdiem;
    private javax.swing.JTextField tdv;
    private javax.swing.JTextField thp;
    private javax.swing.JTextField tht;
    private javax.swing.JTextField tluong;
    private javax.swing.JTextField tma;
    private javax.swing.JTextField tns;
    // End of variables declaration//GEN-END:variables
}
